trade-death-items: false #If this setting is enabled, when a player dies, all items that are dropped will be deleted and sold by wandering traders.
trade-despawned-items: true #If this setting is enabled, when an item despawns, it will be sold by wandering traders.

items:
  blacklist: #Items in this list won't be traded to players
    - COMMAND_BLOCK

  whitelist:
    items:
      - DIAMOND
    enabled: true #If the whitelist is enabled, only items that are in the whitelist will be sold by wandering traders.

  clear-meta: false #If this is enabled, things like enchantments, a custom name and durability of an item will be cleared before the item is added to the trades.

trades:
  buy-limit: 1 #This limits how often players can use a trade
  trade-count: #This changes how many items the wandering trader should sell. A random number between min and max will be generated.
    min: 3
    max: 15
  price: #This changes the price of the trades. A random amount between min and max will be generated.
    min: 3
    max: 20
    item: EMERALD